# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpdateEmployeeTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_updateEmployeeTest(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1104, 809)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .btn-primary").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "email").send_keys("syedowaisahmed22@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-info").click()
  
